version: '3.8'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=todo_db
      - MYSQL_USER=todo_user
      - MYSQL_PASSWORD=todo_password
    depends_on:
      - db
    networks:
      - todo-network

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: todo-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - todo-db-data:/var/lib/mysql
    networks:
      - todo-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: todo-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root_password
    depends_on:
      - db
    networks:
      - todo-network

volumes:
  todo-db-data:

networks:
  todo-network:
    driver: bridge 